title: Sydney Blackmere Portfolio
About me: Graphic Design Student
name: Sydney Blackmere
email: w0727107@myscc.ca
baseurl: "/2025-portfolio"

collections:
  design:
    output: true
    permalink: /:collection/:path/
  photoshop:
    output: true
